// <auto-generated />
using System;
using BackEnd.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.src.Models.Budgets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("expended_value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<decimal>("limit_value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_user");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("BackEnd.src.Models.Pots", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("current_value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<decimal>("target_value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_user");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("BackEnd.src.Models.RecurrentBills", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.Property<int>("paid_installments")
                        .HasColumnType("int");

                    b.Property<string>("recurrence_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_installments")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("RecurrentBills");
                });

            modelBuilder.Entity("BackEnd.src.Models.UserTransactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("creation_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description_tran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_pot")
                        .HasColumnType("int");

                    b.Property<int>("id_recbill")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<string>("pay_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("potid")
                        .HasColumnType("int");

                    b.Property<int?>("recbillid")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("id_user");

                    b.HasIndex("potid");

                    b.HasIndex("recbillid");

                    b.ToTable("UserTransactions");
                });

            modelBuilder.Entity("BackEnd.src.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("expenses")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("income")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("sur_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("cpf")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackEnd.src.Models.Budgets", b =>
                {
                    b.HasOne("BackEnd.src.Models.Users", "user")
                        .WithMany("budgets")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BackEnd.src.Models.Pots", b =>
                {
                    b.HasOne("BackEnd.src.Models.Users", "user")
                        .WithMany("pots")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BackEnd.src.Models.UserTransactions", b =>
                {
                    b.HasOne("BackEnd.src.Models.Users", "user")
                        .WithMany("transactions")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.src.Models.Pots", "pot")
                        .WithMany("transactions")
                        .HasForeignKey("potid");

                    b.HasOne("BackEnd.src.Models.RecurrentBills", "recbill")
                        .WithMany()
                        .HasForeignKey("recbillid");

                    b.Navigation("pot");

                    b.Navigation("recbill");

                    b.Navigation("user");
                });

            modelBuilder.Entity("BackEnd.src.Models.Pots", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("BackEnd.src.Models.Users", b =>
                {
                    b.Navigation("budgets");

                    b.Navigation("pots");

                    b.Navigation("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
